### Create Payment
POST http://localhost:8085/api/v1/payments
Content-Type: application/json

{
  "orderId": "ord-12345",
  "userId": "user-67890",
  "amount": 149.99,
  "currency": "USD",
  "paymentMethod": "CREDIT_CARD"
}

###

### Get Payment by ID
GET http://localhost:8085/api/v1/payments/d50ff4dc-5d30-4788-b849-28b8b13bb635

###

### Update Payment Status
PUT http://localhost:8085/api/v1/payments/1/status
Content-Type: application/json

{
  "status": "PROCESSING"
}

###

### Search Payments
GET http://localhost:8085/api/v1/payments?orderId=ord-12345&page=0&size=10